### ISSUE TITLE
Runtime Error: An attempt has been made to start a new process before the current rocess has finshed its boostrapping phase.

### ISSUE THREAD

**Issue by jponline77** [bclavie/RAGatouille#10]
I attempted the following code:

```from ragatouille import RAGPretrainedModel
import requests

RAG = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")

RAG.index(
    collection= ["This is a test", "Really it's just a test"],
    index_name="Test",
    split_documents=False,
)
```

When I run this I get the following error:

> [Jan 04, 18:44:26] #> Note: Output directory .ragatouille/colbert/indexes/Test already exists
> 
> 
> 
> 
> [Jan 04, 18:44:28] #> Note: Output directory .ragatouille/colbert/indexes/Test already exists
> 
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
>     prepare(preparation_data)
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
>     main_content = runpy.run_path(main_path,
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/runpy.py", line 289, in run_path
>     return _run_module_code(code, init_globals, run_name,
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/runpy.py", line 96, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/jponline77/ragatouille/RAG_2.py", line 6, in <module>
>     RAG.index(
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/site-packages/ragatouille/RAGPretrainedModel.py", line 117, in index
>     return self.model.index(
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/site-packages/ragatouille/models/colbert.py", line 166, in index
>     self.indexer.index(
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/site-packages/colbert/indexer.py", line 78, in index
>     self.__launch(collection)
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/site-packages/colbert/indexer.py", line 83, in __launch
>     manager = mp.Manager()
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/context.py", line 57, in Manager
>     m.start()
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/managers.py", line 562, in start
>     self._process.start()
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
>     return Popen(process_obj)
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>     super().__init__(process_obj)
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
>     prep_data = spawn.get_preparation_data(process_obj._name)
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
>     _check_not_importing_main()
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
>     raise RuntimeError('''
> RuntimeError:
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.
> Traceback (most recent call last):
>   File "/home/jponline77/ragatouille/RAG_2.py", line 6, in <module>
>     RAG.index(
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/site-packages/ragatouille/RAGPretrainedModel.py", line 117, in index
>     return self.model.index(
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/site-packages/ragatouille/models/colbert.py", line 166, in index
>     self.indexer.index(
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/site-packages/colbert/indexer.py", line 78, in index
>     self.__launch(collection)
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/site-packages/colbert/indexer.py", line 83, in __launch
>     manager = mp.Manager()
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/context.py", line 57, in Manager
>     m.start()
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/managers.py", line 566, in start
>     self._address = reader.recv()
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/connection.py", line 250, in recv
>     buf = self._recv_bytes()
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
>     buf = self._recv(4)
>   File "/home/jponline77/miniconda3/envs/rag/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
>     raise EOFError
> EOFError

The following is my torch version:

> Version: 2.1.2
> Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
> Home-page: https://pytorch.org/
> Author: PyTorch Team
> Author-email: packages@pytorch.org
> License: BSD-3
> Location: /home/jponline77/miniconda3/envs/rag/lib/python3.10/site-packages
> Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
> Required-by: RAGatouille, sentence-transformers, torchaudio, torchvision

The following is my cuda version:

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2023 NVIDIA Corporation
> Built on Tue_Feb__7_19:32:13_PST_2023
> Cuda compilation tools, release 12.1, V12.1.66
> Build cuda_12.1.r12.1/compiler.32415258_0

**Comment by okhat** [comment]
) not 100% sure but I think you need to run the code in a block:

```python

if __name__ == "__main__":
    # your code here

```

**Comment by jponline77** [comment]
Thanks!  That worked!

**Comment by okhat** [comment]
Ok let’s keep this open as a reminder to make this clear in the docs. 

And maybe also avoid forking by default if there’s only one gpu?

cc: @bclavie

**Comment by bclavie** [comment]
Thanks for the report! I've added a mention in the README, and will make it more prominent in the next update -- it should've been there to begin with, sorry for the oversight.
