### ISSUE TITLE
`max_tokens` become float after `_set_inference_max_tokens`

### ISSUE THREAD

**Issue by craigkdl** [bclavie/RAGatouille#103]
Hit an error, 
```
TypeError: argument 'max_length': 'float' object cannot be interpreted as an integer
```

After some digging, I found the `max_length` was changed to `281.6`. And with some more digging, it seems this float number comes from https://github.com/bclavie/RAGatouille/blob/864dfb7f95c0160bd0efda00db05c50fd2f7aef9/ragatouille/models/colbert.py#L559

Changing it to 
```
max_tokens = min(
                    math.floor((math.ceil((percentile_90 * 1.35) / 32) * 32) * 1.1),
                    512,
                )
```
fix the error.

**Comment by calebjohn24** [comment]
+1 this fixes this issue

**Comment by bclavie** [comment]
Thank you! This fix made it into the late release, just forgot to update on this issue 😅
