### ISSUE TITLE
Unable to run in replit. Fixed in replit local but cannot deploy

### ISSUE THREAD

**Issue by thisiskeithkwan** [bclavie/RAGatouille#105]
Hi all,

Wanna share my experience trying to make RAGatouille ColBERT run on replit.
I was able to make it running in a fastapi server locally but couldn't deploy on replit

So the error that I received was :

`  File "/home/runner/OslerEM/.pythonlibs/lib/python3.10/site-packages/git/__init__.py", line 142, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Cmd('git') failed due to: exit code(127)
  cmdline: git version
  stderr: 'git: symbol lookup error: /nix/store/dg8mpqqykmw9c7l0bgzzb5znkymlbfjw-glibc-2.37-8/lib/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE'`

After a bit of research I found the answer from [here](https://ask.replit.com/t/an-error-message-appears-when-running-python-code/93979)

change .replit.nix file to
```
{pkgs}: {
  deps = [
    pkgs.libxcrypt
    pkgs.coreutils
  ];
}
```

change .replit file to
```
run = ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
modules = ["python-3.10:v18-20230807-322e88b"]
disableInstallBeforeRun = true
hidden = [".pythonlibs"]

[nix]
channel = "stable-23_05"

[deployment]
run = ["uvicorn", "main:app", "--host", "0.0.0.0"]
deploymentTarget = "gce"

```

Able to run on local but not on deployment, no logs available

**Comment by bclavie** [comment]
Thanks for this report... I'm very unfamiliar with Replit. Your initial error indeed seems like it couldn't build the extension, but not sure why it'd now silently crash.

Leaving this open and hopefully people more familiar than myself will be able to assist! Sorry about this.

**Comment by thisiskeithkwan** [comment]
Thanks @bclavie . 
I am having a ticket running on replit
Will post here for any solution, if founded
