### ISSUE TITLE
Feature Request: Implement chunk_ids feature to Identify chunks.

### ISSUE THREAD

**Issue by nigh8w0lf** [bclavie/RAGatouille#106]
Currently there is no way to differentiate between chunks from the same document as all chunks get the same document_ids.

One use case where this would be useful is when breaking down a query into related sub queries and retrieving relevant chunks for all sub queries and then do de-duplication of the chunks based on chunk_ids.

**Comment by bclavie** [comment]
Good suggestion, thanks! Tagging as Help Wanted/Good First Issue, other I or @anirudhdharmarajan will get on this eventually!
