### ISSUE TITLE
add_to_index  overwrites the previous index 

### ISSUE THREAD

**Issue by kevinningthu** [bclavie/RAGatouille#113]
add_to_index  overwrites the old index, which is similar to the function index(). 
Why it does not reserve the previous indexed documents?

**Comment by kevinningthu** [comment]
code :

from ragatouille.utils import get_wikipedia_page
from ragatouille import RAGPretrainedModel
RAG = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")
full_document = get_wikipedia_page("Hayao_Miyazaki")
len(full_document)
RAG.index(
    collection=[full_document],
    document_ids=['miyazaki'],
    document_metadatas=[{"entity": "person", "source": "wikipedia"}],
    index_name="Miyazaki",
    max_document_length=180,
    split_documents=True
    )

path_to_index = ".ragatouille/colbert/indexes/Miyazaki/"
RAG = RAGPretrainedModel.from_index(path_to_index)
new_documents = get_wikipedia_page("President of Singapore")
RAG.add_to_index([new_documents])
result = RAG.search(query="What animation studio did Miyazaki found?")
print(result)

result:
[{'content': 'The incumbent president is Tharman Shanmugaratnam, who took office on 14 September 2023 after being duly elected in the 2023 presidential election with 70.41% of the vote.\n\n\n== History ==\nThe office of the President of the Republic of Singapore was created on 9 August 1965 when Singapore achieved independence from Malaysia. It succeeded the office of Yang di-Pertuan Negara (lit. "Lord of the State") which was created when Singapore attained self-governance from the British Empire in 1959. The last Yang di-Pertuan Negara, Yusof Ishak, became the first president of Singapore. After his death in 1971, he was succeeded by Benjamin Sheares who was appointed by Parliament and served until his death in 1981.', 'score': 6.6713666915893555, 'rank': 1, 'document_id': 'ffcf942c-e168-4378-9f4e-eb281e6f3afb'}, {'content': "After his death in 1971, he was succeeded by Benjamin Sheares who was appointed by Parliament and served until his death in 1981.\nSheares was succeeded by Devan Nair, who was the Member of Parliament (MP) for Anson SMC from 1979 to 1981, prior to his presidency, who then resigned in 1985. Whilst the apparent reason for Nair's resignation was to seek recovery from his alcoholism, Nair disputes the account, claiming that he was forced out of office by former Prime Minister Goh Chok Tong. Nair was succeeded by Wee Kim Wee, who served as the Ambassador of South Korea and Japan from 1980 to 1984 prior to his presidency until 1993 and was the first president to exercise custodial powers pursuant to the constitutional amendments in 1991.", 'score': 5.959558486938477, 'rank': 2, 'document_id': 'ffcf942c-e168-4378-9f4e-eb281e6f3afb'}, {'content': '"Lord of the State") was created. The office was later succeeded by the President of Singapore after Singapore\'s independence in 1965. The initial role of the president was largely ceremonial and symbolic, carrying residual powers, but the role was later vested with some executive power which includes the reserve power to veto certain bills, most notably in relation to the country\'s reserves as a check and balance process, as well as to revoke and appoint public service appointments among other powers listed in the Constitution.\nPrior to 1991, the president was appointed by Parliament. A constitutional amendment was made that year to allow for the president to be directly elected by a popular vote, which was subsequently first held in 1993. Singapore follows a non-executive model of the Westminster parliamentary system whereby the president is not the head of government but rather the head of state.', 'score': 5.733846664428711, 'rank': 3, 'document_id': 'ffcf942c-e168-4378-9f4e-eb281e6f3afb'}, {'content': 'The president of the Republic of Singapore is the head of state of Singapore. The president represents the country in official diplomatic functions and possesses certain executive powers over the Government of Singapore, including the control of the national reserves and the ability to revoke and appoint public service appointments. The president also holds the prerogative to grant pardons.\nAfter Singapore achieved full internal self-governance from the British Empire in 1959, the ceremonial office of the Yang di-Pertuan Negara (lit. "Lord of the State") was created. The office was later succeeded by the President of Singapore after Singapore\'s independence in 1965.', 'score': 5.596970081329346, 'rank': 4, 'document_id': 'ffcf942c-e168-4378-9f4e-eb281e6f3afb'}, {'content': 'In the early 1980s, the People\'s Action Party (PAP), who at the time occupied all the parliamentary seats in Singapore, suffered their first parliamentary loss in 15 years to the J. B. Jeyaretnam of the Worker\'s Party (WP). As such, then-Prime Minister Lee Kuan Yew became worried that there would one day be a "freak election result" where the PAP would no longer have control over the Parliament and opposition parties would have unfettered access to the government\'s reserves. As such, in January 1991, a constitutional amendment was passed by Parliament to redefine the role of the president.\nThe amendment provided that the president would be elected by a popular vote, subject to strict eligibility requirements.', 'score': 5.593064308166504, 'rank': 5, 'document_id': 'ffcf942c-e168-4378-9f4e-eb281e6f3afb'}, {'content': 'Speaking in Parliament on 10 March 2011, Minister for Finance Tharman Shanmugaratnam explained that this sum was to cater for the salaries of an additional staff officer to support the work of the Council of Presidential Advisers, and a butler manager; and to meet higher variable staff salary payments due to the nation\'s strong economic growth. The allowance for the Istana\'s household expenses (Class III) is $2,762,308, an increase from $694,000. This allowance is used to cover the maintenance of the Istana, vehicles, utilities and other supplies, as well as for ceremonies and celebrations. The increase was to cater for higher expenses for maintaining computer systems, buildings and land, and to account for inflation.Class IV expenses for "special services" are $550,000.', 'score': 5.444579124450684, 'rank': 6, 'document_id': 'ffcf942c-e168-4378-9f4e-eb281e6f3afb'}, {'content': 'She was the sole eligible candidate under the new reform terms which took effect earlier that year. Yacob was also the first Malay head of state in 47 years since the death of the first president of Singapore, Yusof Ishak, and the first female President of Singapore.On 1 September 2023, Tharman Shanmugaratnam, who served as Senior Minister from 2019 to 2023, prior to his presidency, won the 2023 presidential election and was elected the ninth President of Singapore after receiving 70.41% of the votes cast.In November 2023, the parliament of Singapore passed a bill to amend the constitution to allow the President of Singapore to hold international positions in their private capacity, only if the position is of national interest.\n\n\n== Constitutional role ==\nThe president is the head of state of Singapore.', 'score': 5.399357318878174, 'rank': 7, 'document_id': 'ffcf942c-e168-4378-9f4e-eb281e6f3afb'}, {'content': 'He was sworn in as the seventh president of Singapore on 1 September 2011. Ong Teng Cheong and Tony Tan are the only Deputy Prime Minister who became presidents.\nIn 2016, further amendments to the Constitution were passed providing for "reserved elections" for a particular ethnic community, if that community has not provided a president in the past five presidential terms.\nThe eighth president, Halimah Yacob, who served as Speaker of Parliament from 2013 to 2017, prior to her presidency, took office on 14 September 2017. She was the sole eligible candidate under the new reform terms which took effect earlier that year.', 'score': 5.084346294403076, 'rank': 8, 'document_id': 'ffcf942c-e168-4378-9f4e-eb281e6f3afb'}, {'content': "The Elections Department published the overseas vote count on 12 September. Only 3,799 votes were accepted for counting, of which only 78 votes were rejected. Tharman Shanmugaratnam, Ng Kok Song, and Tan Kin Lian garnered 2,834, 595, and 292 votes, respectively, which saw only a 0.01% change in Tharman's and Tan's respective voting percentages. ELD also said that 2,997 postal votes had been downloaded and 2,263 mails were received as of the cut-off date of 11 September, of which only 1,345 had been accepted. The final turnout was 2,534,711, increasing its percentage by 0.14%, from 93.41% to 93.55%.The final results are as follows:", 'score': 5.001492500305176, 'rank': 9, 'document_id': 'ffcf942c-e168-4378-9f4e-eb281e6f3afb'}, {'content': '== Further reading ==\n\n\n=== Articles ===\nLee, Yvonne C.L. (2007), "Under Lock and Key: The Evolving Role of the Elected President as a Fiscal Guardian", Singapore Journal of Legal Studies: 290–322, SSRN 1139305.\nWan, Wai Yee (1994), "Recent Changes to the Westminster System of Government and Government Accountability", Singapore Law Review, 15: 297–332.\n\n\n=== Books ===\nChan, Helena H[ui-]M[eng] (1995), "The Executive", The Legal System of Singapore, Singapore: Butterworths Asia, pp. 22–29, ISBN 978-0-409-99789-7.', 'score': 4.895559310913086, 'rank': 10, 'document_id': 'ffcf942c-e168-4378-9f4e-eb281e6f3afb'}]

**Comment by bclavie** [comment]
Hey, thank you for flagging this! This is the same issue as in https://github.com/bclavie/RAGatouille/issues/71 and was recently introduced -- it should be fixed relatively soon with more CRUD updates.
