### ISSUE TITLE
Updating to latest version download what it seems excessive dependencies.... 

### ISSUE THREAD

**Issue by GMartin-dev** [bclavie/RAGatouille#120]
Updating to 0.0.6b2 downloaded what it seems like an overkill amount of dependencies  several GBs of cuda, nvidia, etc... when before it was running without all this... 
Are this new dependencies forced b latest COLbert?
Is there a way to force only download dependencies to run on CPU?
![image](https://github.com/bclavie/RAGatouille/assets/1821407/67a5f03f-12ef-4c02-93cb-b15c9c3f69a9)
![image](https://github.com/bclavie/RAGatouille/assets/1821407/78df33f7-07c5-4cfc-b622-3729e4533e6e)

It seems that also introduced regression, search stopped working.... it seems that it hangs loading an extension:

```
[Feb 07, 01:04:43] Loading segmented_maxsim_cpp extension (set COLBERT_LOAD_TORCH_EXTENSION_VERBOSE=True for more info)...
Using /home/german/.cache/torch_extensions/py311_cu117 as PyTorch extensions root...
Emitting ninja build file /home/german/.cache/torch_extensions/py311_cu117/segmented_maxsim_cpp/build.ninja...
Building extension module segmented_maxsim_cpp...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module segmented_maxsim_cpp...
/home/german/.pyenv/versions/3.11.3/envs/agile_clean/lib/python3.11/site-packages/torch/cuda/amp/grad_scaler.py:120: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
/home/german/.pyenv/versions/3.11.3/envs/agile_clean/lib/python3.11/site-packages/torch/cuda/amp/grad_scaler.py:120: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
Loading searcher for index test_tickets_full_text_all for the first time... This may take a few seconds
/home/german/.pyenv/versions/3.11.3/envs/agile_clean/lib/python3.11/site-packages/torch/cuda/amp/grad_scaler.py:120: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
[Feb 07, 01:05:06] #> Loading codec...
[Feb 07, 01:05:06] #> Loading IVF...
[Feb 07, 01:05:06] Loading segmented_lookup_cpp extension (set COLBERT_LOAD_TORCH_EXTENSION_VERBOSE=True for more info)...
Using /home/german/.cache/torch_extensions/py311_cu117 as PyTorch extensions root...
Emitting ninja build file /home/german/.cache/torch_extensions/py311_cu117/segmented_lookup_cpp/build.ninja...
Building extension module segmented_lookup_cpp...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module segmented_lookup_cpp...
[Feb 07, 01:05:06] #> Loading doclens...
100%|███████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 2388.56it/s]
[Feb 07, 01:05:06] #> Loading codes and residuals...
100%|████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 316.55it/s]
[Feb 07, 01:05:06] Loading filter_pids_cpp extension (set COLBERT_LOAD_TORCH_EXTENSION_VERBOSE=True for more info)...
Using /home/german/.cache/torch_extensions/py311_cu117 as PyTorch extensions root...
Emitting ninja build file /home/german/.cache/torch_extensions/py311_cu117/filter_pids_cpp/build.ninja...
Building extension module filter_pids_cpp...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module filter_pids_cpp...
[Feb 07, 01:05:06] Loading decompress_residuals_cpp extension (set COLBERT_LOAD_TORCH_EXTENSION_VERBOSE=True for more info)...
Using /home/german/.cache/torch_extensions/py311_cu117 as PyTorch extensions root...

```

**Comment by bclavie** [comment]
Forgot to mention but:
> Is there a way to force only download dependencies to run on CPU?
I'm looking into this! It's a bit annoying but I'm looking into either having a `[gpu]` or `[cpu]` install flag to avoid both being the default.

**Comment by GMartin-dev** [comment]
@bclavie Thanks for you response! I was playing with this and I found a work around.
Pre installed torch hardcoding the cpu tag:
pip install --no-cache-dir torch==2.2.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
then installed sentence_transformers, transformers, etc.
Then RAGatouille.... 
All Cuda/Nvidia libraries are gone and the index was back to working properly.

**Comment by bclavie** [comment]
> @bclavie Thanks for you response! I was playing with this and I found a work around. Pre installed torch hardcoding the cpu tag: pip install --no-cache-dir torch==2.2.0+cpu -f https://download.pytorch.org/whl/torch_stable.html then installed sentence_transformers, transformers, etc. Then RAGatouille.... All Cuda/Nvidia libraries are gone and the index was back to working properly.

Yeah this is what I figured! I think in an upcoming "major" release I'm going to remove a lot of dependencies from the main library, and add very visible warning messages about no backend being installed if no version of `torch` is present, similar to huggingface transformers. This hopefully will only slightly increase the barrier to entry but greatly help with _a lot_ of dependency issues.

**Comment by Lalit439cs** [comment]
@bclavie we are still facing hanging issue at this point while indexing or RAG.search-
`Loading decompress_residuals_cpp extension (set COLBERT_LOAD_TORCH_EXTENSION_VERBOSE=True for more info)...`

we are working with ragatouille version- 0.0.8.post4

**Comment by nguyen-van-hieu** [comment]
You might be encountering this issue due to a corrupted or outdated PyTorch extension build. Try clearing the local Torch extensions cache by running the following command:

`rm -rf ~/Library/Caches/torch_extensions
`

Then re-run your script with verbose output enabled to get more detailed logs:

`export COLBERT_LOAD_TORCH_EXTENSION_VERBOSE=True && python main.py
`
