### ISSUE TITLE
Cannot access pre-trained ColBERT model on Windows 11 (CPU-only)

### ISSUE THREAD

**Issue by adisarun30** [bclavie/RAGatouille#127]
I tried to import the ColBERT model and got a DLL related error on Windows 11 PC (attached screenshot). It doesn't have a discrete GPU. 

I Googled the error message and installed Visual C++ distribution but that didn't help either.

Could anyone please help me with this?

![image](https://github.com/bclavie/RAGatouille/assets/13044139/03fdcf75-580c-4067-a21b-44c77633dd45)

**Comment by okhat** [comment]
Try again. HF model hub was down

**Comment by bclavie** [comment]
Hey, this is a windows-specific issue. We don't guarantee windows support at the moment but it seems like your problem is still that there's an issue properly loading the require CPP DLL to use the custom code.
