### ISSUE TITLE
Can't search with k over 128

### ISSUE THREAD

**Issue by ABCbum** [bclavie/RAGatouille#130]
Hi, I encountered an issue when searching with k > 128, it always returns a **maximum** of 128 results. Is this a known limitation or is there any configuration should pay attention to?

Some information: 
- The dataset has 800 docs.
- Model: colbert-ir/colbertv2.0
- Code:
```py
from ragatouille import RAGPretrainedModel

# Indexing
RAG = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")
index_path = RAG.index(index_name="my_index", collection=docs, document_ids=doc_ids)

# Retrieving
RAG = RAGPretrainedModel.from_index('.ragatouille/colbert/indexes/my_index')
results = RAG.search(query, k=200)
print(len(results))
# -> 128
```

Please let me know if you need more information. Thanks a lot for the help!

**Comment by okhat** [comment]
need to use a larger value for ncells  cc: @bclavie

**Comment by bclavie** [comment]
Well spotted, both ncells and ndocs weren't very well set up for larger k values. Will be fixed in https://github.com/bclavie/RAGatouille/pull/131 and (upcoming) associated release 0.0.6c2
