### ISSUE TITLE
You have a GPU available, but only `faiss-cpu` is currently installed.

### ISSUE THREAD

**Issue by sungkim11** [bclavie/RAGatouille#141]
I am getting this warning then it uses CPU to create indexes.

WARNING! You have a GPU available, but only `faiss-cpu` is currently installed.
 This means that indexing will be slow. To make use of your GPU.
Please install `faiss-gpu` by running:
pip uninstall --y faiss-cpu & pip install faiss-gpu
 ________________________________________________________________________________
Will continue with CPU indexing in 5 seconds...

I have faiss-gpu installed, not faiss-cpu.

**Comment by bclavie** [comment]
Hey, there seems to be an issue with the attribute that we use as a proxy to check whether faiss has GPU bindings or not. This should be purely an annoyance with no actual impact (i.e. the GPU will be used in spite of the message). I'll update this in the next fix release, thank you!

**Comment by sungkim11** [comment]
For me, it is more than annoyance since the embedding/index process does not use GPU.

**Comment by bclavie** [comment]
Oh, this is particularly odd then, as the use of faiss in RAGatouille is limited to checking if it has a GPU-related attribute, and the rest is handled upstream 🤔. Could you run `pip-freeze` to make sure there's no conflicting faiss versions? (It's happened to me before where both `faiss-gpu` and `faiss-cpu` were present, and caused some conflicts).

If there's no conflict, it'd be really helpful if you could get your env details (OS, Python version, CUDA version, GPU used, pip freeze) and create an issue on https://github.com/stanford-futuredata/ColBERT about the GPU not being used! Thanks a lot and sorry about the issue.

**Comment by labdmitriy** [comment]
Hi @bclavie,

Maybe the reason of this problem is that you have faiss-cpu as [requirement](https://github.com/bclavie/RAGatouille/blob/6261f85e73617ff313745b1fc509b1cd1dbce544/pyproject.toml#L14) while ColBERT itself has both faiss-cpu and faiss-gpu as [extras](https://github.com/stanford-futuredata/ColBERT/blob/852271661b22567e3720f2dd56b6d503613a3228/setup.py#L34-L35).

So probably if you use the same approach for [poetry](https://python-poetry.org/docs/pyproject/#extras) then the user will be able to choose which version of faiss to install.

Thank you.

**Comment by RhizoNymph** [comment]
Even when I remove faiss-cpu and install faiss-gpu via conda it doesn't work but at that point I get "WARNING: faiss must be imported for indexing" so this can't be resolved just by making sure the right package is present.

**Comment by labdmitriy** [comment]
Hi,

I removed faiss-cpu, installed faiss-gpu, restarted kernel an rerun all the code - it works without warning.

Thank you.

**Comment by bclavie** [comment]
Hey all!

Sorry for the delays, a lot has been going on!

So, to be honest, maintaining `faiss` in a user-facing lib has been a bit of a nightmare. I've taken a few dives trying to fix it and I can somewhat consistently get it to work on my machine(s), but I'm not seeing a clear path to making it work out-of-the-box for all (or nearly all) users, so I'm trying to move away from it faster than intended, at least for most usecases (small-to-medium collections).

#173 replaces FAISS with pure PyTorch, which should remove all those compatibility issues. It gets results within a very small tolerant of FAISS-kmeans in my tests, but I'd be grateful for any feedback on results accuracy (or even overall functionality) if you have any time to do so!

**Comment by RhizoNymph** [comment]
Love to hear this, I've been really frustrated with how fussy faiss is. I'll try to get this running on the machine I was having trouble with and report back on compatibility. Will also try to get a benchmark set up to compare!

**Comment by bclavie** [comment]
V0.0.8 is out and does bypass faiss in favour of PyTorch kmeans for collections with fewer than 100k documents!

I'd still consider this feature experimental, but it seems to be a pretty solid way to try out PLAID in different environments without figuring out how to make faiss play nice with this environment.

Benchmark results were pretty much identical in the few we tried, but we're very much looking for feedback if your experience doesn't (or does!) match this @RhizoNymph.

**Comment by RhizoNymph** [comment]
@bclavie It works great for me on the machine where faiss has been giving me problems! I wrote a short benchmark script I'm going to set up on the machine that I have faiss working on, will report back with comparisons.
