### ISSUE TITLE
TypeError: array([15055,   320, 22479,  2853,  8197,    ...,   374,  3827]) is not JSON serializable

### ISSUE THREAD

**Issue by sungkim11** [bclavie/RAGatouille#143]
I am using jinaai/jina-colbert-v1-en with max_document_length=1024 to create an index. This works when I use max_document_length=512.

Everything works well then I get a TypeError at the end.

Saved optimized IVF to .ragatouille/colbert/indexes/publications_512_384_jina_colbert/ivf.pid.pt
Traceback (most recent call last):
  File "/envpath/create_embedding_ragatouille.py", line 42, in <module>
    index_path = RAG.index(
  File "/envpath/lib/python3.10/site-packages/ragatouille/RAGPretrainedModel.py", line 183, in index
    return self.model.index(
  File "/envpath/lib/python3.10/site-packages/ragatouille/models/colbert.py", line 390, in index
    self._write_collection_to_file(
  File "/envpath/colbert/lib/python3.10/site-packages/ragatouille/models/colbert.py", line 119, in _write_collection_to_file
    srsly.write_json(collection_path, collection)
  File "/envpath/lib/python3.10/site-packages/srsly/_json_api.py", line 88, in write_json
    json_data = json_dumps(data, indent=indent)
  File "/envpath/lib/python3.10/site-packages/srsly/_json_api.py", line 26, in json_dumps
    result = ujson.dumps(data, indent=indent, escape_forward_slashes=False)
TypeError: array([15055,   320, 22479,  2853,  8197,     8,   374,  3827,  1949]) is not JSON serializable

**Comment by bclavie** [comment]
Thank you for flagging! Will try and figure out what's going on as soon as I have a bit more time and report. In the meantime, flagging as `Help Wanted` in case someone has time to address the issue -- I don't think it'll be too hard to debug.

**Comment by jlscheerer** [comment]
@sungkim11 happy to look into this. Do you perhaps have a (minimal) code to reproduce the issue? Running an adpated version of the indexing code outlined [here](https://github.com/bclavie/RAGatouille?tab=readme-ov-file#%EF%B8%8F-indexing) works perfectly fine for me (with either `max_document_length=1024` or `max_document_length=512`):

```python3
RAG = RAGPretrainedModel.from_pretrained("jinaai/jina-colbert-v1-en")
my_documents = [
    get_wikipedia_page("Hayao_Miyazaki"),
    get_wikipedia_page("Studio_Ghibli"),
]
document_ids = ["miyazaki", "ghibli"]
document_metadatas = [
    {"entity": "person", "source": "wikipedia"},
    {"entity": "organisation", "source": "wikipedia"},
]
index_path = RAG.index(
    index_name="my_index",
    collection=my_documents,
    document_ids=document_ids,
    document_metadatas=document_metadatas,
    max_document_length=1024,
)
```

**Comment by sungkim11** [comment]
Thank you for responding.

I hope this code is helpful. This code when I set "max_document_length=512" work, but fails when set to "max_document_length=1024":

import pandas as pd
from ragatouille import RAGPretrainedModel

# Load the Parquet file
df = pd.read_parquet('db.parquet')

# Assuming 'text' is your document content and 'document_id' is the unique identifier
document_texts = df['text'].tolist()
document_ids = df['chunk_id'].tolist()

# Exclude 'text' and 'document_id' from metadata
metadata_columns = df.columns.difference(['id', 'title', 'subtitle'])

# Construct document metadata
document_metadatas = df[metadata_columns].apply(lambda row: row.to_dict(), axis=1).tolist()

# Initialize the RAG model

RAG = RAGPretrainedModel.from_pretrained("jinaai/jina-colbert-v1-en")

# Index the documents with their IDs and metadata
index_path = RAG.index(    
    index_name="db_384_jina_colbert",
    collection=document_texts,
    document_ids=document_ids,
    document_metadatas=document_metadatas,
    max_document_length=1024,
    overwrite_index=True,
)

**Comment by jlscheerer** [comment]
Thank you for sharing the code @sungkim11. I am still failing to reproduce your issue. The following works perfectly fine for me:
```python3
# Write data to the Parquet file.
df = pd.DataFrame(
    data={
        "title": ["Hayao_Miyazaki", "Studio_Ghibli"],
        "text": [
            get_wikipedia_page("Hayao_Miyazaki"),
            get_wikipedia_page("Studio_Ghibli"),
        ],
        "chunk_id": ["Chunk1", "Chunk2"],
        "subtitle": ["Subtitle1", "Subtitle2"],
        "metadata1": ["Metadata1.1", "Metadata1.2"],
        "metadata2": ["Metadata2.1", "Metadata2.2"],
    }
)
df.to_parquet("db.parquet")
df = pd.read_parquet("db.parquet")
document_texts = df["text"].tolist()
document_ids = df["chunk_id"].tolist()

metatdata_columns = df.columns.difference(["id", "title", "subtitle"])

document_metadatas = (
    df[metatdata_columns].apply(lambda row: row.to_dict(), axis=1).tolist()
)

RAG = RAGPretrainedModel.from_pretrained("jinaai/jina-colbert-v1-en")
index_path = RAG.index(
    index_name="db_384_jina_colbert",
    collection=document_texts,
    document_ids=document_ids,
    document_metadatas=document_metadatas,
    max_document_length=1024,
    overwrite_index=True,
)
```

The only way I have found to reproduce your issue is by explicitly creating an index with invalid/unserializable metadata (e.g., by setting `"metadata2": [np.array([1, 2]), np.array([4, 5])]`).

As your error message most likely indicates an error during serialization of the document metadata ([here](https://github.com/bclavie/RAGatouille/blob/b7ae28a246cdb0813d87de903f03358642a33060/ragatouille/models/colbert.py#L390)), which is not directly impacted by document splitting - as specified via `max_document_length` - it's very difficult to debug without further information.

Are you by chance attempting to store np.array's as part of the metadata or using an older version of the library?

**Comment by sungkim11** [comment]
Let me look into my dataset. Thank you for looking into this.
