### ISSUE TITLE
Pytorch 2.1 on Runpod running Examples hangs with message

### ISSUE THREAD

**Issue by grahama1970** [bclavie/RAGatouille#146]
Hi. I'm trying to run Ragatouille examples off a pytorch 2.1 template with 2 A6000 GPUs. On the  basic_indexing_and_searching example, it hangs and produces the below output:
The examples do work without issues in a free Google collab....just not on WSL or on the Runpod, yet :)
runpod.io
template: pytorch 2.1
runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04
2 x RTX A6000
63 vCPU 117 GB RAM
<img width="721" alt="image" src="https://github.com/bclavie/RAGatouille/assets/152222635/bf3c9349-44cd-4bd8-acfd-48f0a54f82ac">

Any help is appreciated

#> Starting...
#> Starting...
nranks = 2 	 num_gpus = 2 	 device=1
nranks = 2 	 num_gpus = 2 	 device=0
[Feb 19, 15:15:52] [1] 		 #> Encoding 40 passages..
[Feb 19, 15:15:52] [0] 		 #> Encoding 41 passages..
[Feb 19, 15:15:53] [0] 		 avg_doclen_est = 129.80091857910156 	 len(local_sample) = 41
[Feb 19, 15:15:53] [1] 		 avg_doclen_est = 129.80091857910156 	 len(local_sample) = 40
[Feb 19, 15:15:53] [0] 		 Creating 1,024 partitions.
[Feb 19, 15:15:53] [0] 		 *Estimated* 10,513 embeddings.
[Feb 19, 15:15:53] [0] 		 #> Saving the indexing plan to .ragatouille/colbert/indexes/Miyazaki/plan.json ..
Clustering 9991 points in 128D to 1024 clusters, redo 1 times, 20 iterations
  Preprocessing in 0.00 s
WARNING clustering 9991 points to 1024 centroids: please provide at least 39936 training points
Faiss assertion 'err == CUBLAS_STATUS_SUCCESS' failed in void faiss::gpu::runMatrixMult(faiss::gpu::Tensor<float, 2, true>&, bool, faiss::gpu::Tensor<T, 2, true>&, bool, faiss::gpu::Tensor<IndexType, 2, true>&, bool, float, float, cublasHandle_t, cudaStream_t) [with AT = float; BT = float; cublasHandle_t = cublasContext*; cudaStream_t = CUstream_st*] at [/project/faiss/faiss/gpu/utils/MatrixMult-inl.cuh:265](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225079746f7263682d52756e706f64227d.vscode-resource.vscode-cdn.net/project/faiss/faiss/gpu/utils/MatrixMult-inl.cuh:265); details: cublas failed (13): (512, 128) x (1024, 128)' = (512, 1024) gemm params m 1024 n 512 k 128 trA T trB N lda 128 ldb 128 ldc 1024
Faiss assertion 'err == CUBLAS_STATUS_SUCCESS' failed in void faiss::gpu::runMatrixMult(faiss::gpu::Tensor<float, 2, true>&, bool, faiss::gpu::Tensor<T, 2, true>&, bool, faiss::gpu::Tensor<IndexType, 2, true>&, bool, float, float, cublasHandle_t, cudaStream_t) [with AT = float; BT = float; cublasHandle_t = cublasContext*; cudaStream_t = CUstream_st*] at [/project/faiss/faiss/gpu/utils/MatrixMult-inl.cuh:265](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a225079746f7263682d52756e706f64227d.vscode-resource.vscode-cdn.net/project/faiss/faiss/gpu/utils/MatrixMult-inl.cuh:265); details: cublas failed (13): (512, 128) x (1024, 128)' = (512, 1024) gemm params m 1024 n 512 k 128 trA T trB N lda 128 ldb 128 ldc 1024

**Comment by grahama1970** [comment]
On my end, I'm happy to test any patches/fixes, and send back a bug report :) look forward to trying ratatouille out!

**Comment by grahama1970** [comment]
Question to all--is there a runpod template that will run Ragatouille without error?

**Comment by grahama1970** [comment]
No worries. I'm happy to try a different runpod template, and send you the logs. At this point, I'm unable to test Ragatouille on WSL 2 (windows) or on a runpod. I look forward to getting Ragatouille working!btw, it does work in a google Collab--which is not part of my normal flow/pipeline.

**Comment by bclavie** [comment]
This should be fixed in [0.0.8](https://github.com/bclavie/RAGatouille/releases/tag/0.0.8), as long as you are indexing fewer than ~100k documents (with the new tentative faiss replacement just using PyTorch to perform k-means).
