### ISSUE TITLE
ImportError: cannot import name 'Document' from 'llama_index' (unknown location)

### ISSUE THREAD

**Issue by alokkrsahu** [bclavie/RAGatouille#152]
https://github.com/bclavie/RAGatouille/blob/main/ragatouille/data/preprocessors.py

**Comment by bclavie** [comment]
Hey, what version of `llama-index` are you using? It seems like they've updated some things on their end, will work on a fix! Also related https://github.com/bclavie/RAGatouille/issues/147

**Comment by logan-markewich** [comment]
@bclavie LlamaIndex maintainer here -- v0.10.x is a bit of a breaking change in terms of imports. Let me know if you need a hand with handling any migration :)

**Comment by bclavie** [comment]
Hey @logan-markewich, I think all we're really using right now is the document splitter & the `Document` object.  I could dig but I assume you're a lot more familiar than I am -- any recommendations in keeping the overall behaviour [here](https://github.com/bclavie/RAGatouille/blob/main/ragatouille/data/preprocessors.py) with imports compatible with both the new version and older ones?

**Comment by logan-markewich** [comment]
Probably just need a try except 

```
try:
  from llama_index import Document
  from llama_index.text_splitter import SentenceSplitter
except ImportError:
  from llama_index.core import Document
  from llama_index.core.text_splitter import SentenceSplitter

```

That should work for both v0.10.x and older versions

**Comment by bclavie** [comment]
Thanks! Fixed in https://github.com/bclavie/RAGatouille/pull/155 (0.0.7post5)

**Comment by RibinMTC** [comment]
Hi, I'm encountering the same issue with the error: `ImportError: cannot import name 'Document' from 'llama_index.core' (unknown location)`
Ragatouille version: _0.0.7.post5_ 
llama-index version: _0.9.48._

**Comment by Balavarun5** [comment]
Hi @RibinMTC , I too faced similar issue. Here's how i fixed it
1. uninstall ragatouille
2. reinstall with pip install git+https://github.com/bclavie/RAGatouille/
3. modify the file /path/to/venv/lib/python3.10/site-packages/ragatouille/data/preprocessors.py line 5 to ```from llama_index.core.schema import Document```

**Comment by logan-markewich** [comment]
Yea, either that or starting with a fresh venv is probably the ideal solution here

**Comment by atang31** [comment]
For me I just had to make sure `setuptools` is also required.
ragatouille: 0.0.7.post11
llama-index: 0.9.48

**Comment by akshay6893** [comment]
Now the error looks like this - 

`Plain typing.TypeAlias is not valid as type argument`

Just adding it so people searching it will be able to find this thread.

Also i changed ( in the package ) i.e `RAGatouille/blob/main/ragatouille/data/preprocessors.py` - 

From : 
` from llama_index.core import Document  `
`from llama_index.core.text_splitter import SentenceSplitter`

To:

`from llama_index.legacy import Document`
`from llama_index.legacy.text_splitter import SentenceSplitter`

**Comment by fabiannagel** [comment]
Still running into the `ImportError` with `ragatouille==0.0.8post2`. Why don't we narrow down the version of `llama-index` to reduce the risk of pulling breaking changes? `">=0.7, <=0.10"` worked great for me so far.

See https://github.com/bclavie/RAGatouille/pull/227
