### ISSUE TITLE
examples/06-index_free_use.ipynb _ TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by ten2mushi** [bclavie/RAGatouille#164]
When running ex06 for in memory use, I ran into this error originating from _set_inference_max_tokens():

line : if max_tokens > self.base_model_max_tokens:
msg: TypeError: '>' not supported between instances of 'str' and 'int'

I tested this edit to _set_inference_max_tokens() and seems to work for the example

    def _set_inference_max_tokens(
        self, documents: list[str], max_tokens: Union[Literal["auto"], int] = "auto"
    ):
        if (
            not hasattr(self, "inference_ckpt_len_set")
            or self.inference_ckpt_len_set is False
        ):
            if max_tokens == "auto":
                max_tokens = self.base_model_max_tokens
            else:
                max_tokens = int(max_tokens)

            if max_tokens > self.base_model_max_tokens:
                max_tokens = self.base_model_max_tokens

            percentile_90 = np.percentile(
                [len(x.split(" ")) for x in documents], 90
            )
            max_tokens = min(
                math.floor((math.ceil((percentile_90 * 1.35) / 32) * 32) * 1.1),
                self.base_model_max_tokens,
            )
            max_tokens = max(256, max_tokens)

            if max_tokens > 300:
                print(
                    f"Your documents are roughly {percentile_90} tokens long at the 90th percentile!",
                    "This is quite long and might slow down reranking!\n",
                    "Provide fewer documents, build smaller chunks or run on GPU",
                    "if it takes too long for your needs!",
                )
            self.inference_ckpt.colbert_config.max_doclen = max_tokens
            self.inference_ckpt.doc_tokenizer.doc_maxlen = max_tokens
            self.inference_ckpt_len_set = True

**Comment by bclavie** [comment]
Thanks for flagging! Should be fixed in [0.0.8](https://github.com/bclavie/RAGatouille/releases/tag/0.0.8)
