### ISSUE TITLE
Bug in _invert_pid_docid_map

### ISSUE THREAD

**Issue by xhw1** [bclavie/RAGatouille#178]
Should probably be:

```python
def _invert_pid_docid_map(self) -> Dict[str, List[int]]:
    d = defaultdict(list)
    for k, v in self.pid_docid_map.items():
        d[v].append(k)
    return d
```

**Comment by bclavie** [comment]
You're completely correct, the doc_id --> pid relationship should be one-to-many, not one-to-one. Thanks for flagging, implementing in #179 and will release as a minor fix version (0.0.8post2)
