### ISSUE TITLE
jinaai/jina-colbert-v1-en vs colbert-ir/colbertv2.0 when to use what

### ISSUE THREAD

**Issue by karthikgali** [bclavie/RAGatouille#193]
Hi,

Thank you for developing this toolkit, which has been immensely helpful. I have a basic question regarding when to use jinaai/jina-colbert-v1-en versus colbert-ir/colbertv2.0. Could someone provide documentation on performance metrics and quality metrics?

Regards,
Karthik

**Comment by bclavie** [comment]
Hey, I'd also add https://huggingface.co/mixedbread-ai/mxbai-colbert-large-v1 to the list of models you consider! They provide a comparison of all three models on their huggingface page as well, which I think will answer your question as to which model to use!
