### ISSUE TITLE
What should I do if I want a blank, untrained ColBRET?

### ISSUE THREAD

**Issue by jmnian** [bclavie/RAGatouille#206]
I have some data. My goal is to train from a vanilla version of ColBERT that uses the `bert-base-uncased` as the encoder, and the linear layer parameters are randomly initialized. I would love to leverage RAGatouille's utilities for the ease of training. Thank you for pointing me to the right direction. 
When initializing the trainer I'm using this: 
`trainer = RAGTrainer(model_name=model_name, 
                        pretrained_model_name = "colbert-ir/colbertv1.9",
                        language_code='en',
                        n_usable_gpus=1
                        )`

Does `colbertv1.9` mean I am using an untrained ColBERT? Is there any way I can use RAGatouille to accomplish my goal?

**Comment by bclavie** [comment]
Hey! The way to start the trainer from a completely untrained ColBERT would be just specifying whatever base model you want to use as an argument to `pretrained_model_name`. So in your case, you'd run it as `pretrained_model_name='bert-base-uncased'`.
