### ISSUE TITLE
Ability to store metadata with the content

### ISSUE THREAD

**Issue by mrshu** [bclavie/RAGatouille#28]
First of all, thanks a bunch for `RAGatouille` -- it's been a very nice library to make use of in some of the experiments I've been doing lately!

One feature I was missing was the ability to store some metadata (e.g. the source of the content or some other attribute) in the index -- similarly how one would do so within `chromadb` for instance (https://docs.trychroma.com/getting-started#4-add-some-text-documents-to-the-collection).

Do you think something like that would be possible? If so, feel free to leave some pointers -- I'd be happy to see if I can contribute a quick PR with it.

Thanks!

**Comment by bclavie** [comment]
Hey @mrshu, thank you for suggesting this, and thank you for the kind words 😊 

This is pretty similar to the feature requested in https://github.com/bclavie/RAGatouille/issues/25 so I'll close this issue to centralise things there!

I left a comment there about how we could easily implement disk (by following the on-disk storage approach ColBERT uses), it should be really straightforward -- just have to make sure `models.colbert` has a way to accept&export metadatas, and that it's loaded properly so it can be returned by `search()`.
