### ISSUE TITLE
Qdrant Support?

### ISSUE THREAD

**Issue by jordanparker6** [bclavie/RAGatouille#35]
Qdrant supports sparse vectors.

Is it possible to get COLBERTv2 supported with Qdrant as a storage layer?

**Comment by bclavie** [comment]
Hey!

I'm not currently working on direct support for specific storage solutions as it's a lot of work for a subsection of users. I'm not super familiar with Qdrant itself, so will leave the issue open for people more familiar with the matter to check out (or for myself to try out at a later point).
