### ISSUE TITLE
Utilizing clustering

### ISSUE THREAD

**Issue by rawsh** [bclavie/RAGatouille#64]
Hi, sorry if this is an ignorant question but would it be possible to use the calculated centroids for nlp tasks such as summarization? With dense embeddings it's possible to cluster the dataset and use documents close to the centroids from each cluster as a representation of the cluster for summarization. Would it be possible to do something similar with the centroids calculated by ragatouille?

**Comment by okhat** [comment]
Amazing question. Maybe the answer can become yes with some exploration!

But right now, it’s tricky. The centroids are for tokens, not whole documents

**Comment by rawsh** [comment]
@okhat Thank you very much for the insight! Will try to look into this at some point. Closing for now.
