### ISSUE TITLE
Documentation for max supported document length

### ISSUE THREAD

**Issue by rawsh** [bclavie/RAGatouille#67]
Testing with larger documents gives this error:
```
RuntimeError: The expanded size of the tensor (812) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [64, 812].  Tensor sizes: [1, 512]
```
What is the largest document length supported? Looks like splitting for chunk_size=800 works but chunk_size=1000 fails.

**Comment by bclavie** [comment]
Hey, the max text length isn't inherent to RAGatouille and depends on the model you use. 
Most (all?) existing ColBERT models are spun off a normal BERT or RoBERTa models rather than longer context models, so they can take up to 512 tokens.
