### ISSUE TITLE
Support CPU

### ISSUE THREAD

**Issue by rubenaros** [bclavie/RAGatouille#69]
Hi, i want to run RAGatouille with cpu, It's possible?  I don't see any parameter to define the device.

Thanks in advance

**Comment by bclavie** [comment]
Hey!

Clearer documentation and user-definable device is something that we'll be including in the future for clarity. It will require a few more changes to the upstream ColBERT repo first!

At the moment, the upstream repo handles device assignment. There is CPU support for indexing, searching and re-ranking, but not for training. Hope this helps!
