### ISSUE TITLE
Querying on Subset of Document_IDs

### ISSUE THREAD

**Issue by PrimoUomo89** [bclavie/RAGatouille#83]
Would love to be able to pass in an array of document_IDs as argument to query function, representing the subset of documents to query. Not familiar enough with the inner workings of the technology to propose a resolution myself. Would gladly take some guidance from someone more senior so I can produce a pull request myself.

**Comment by bclavie** [comment]
Hey, this is a great suggestion and has already been requested!

It's doable without too many code changes because ColBERT natively supports querying only a subset of passage IDs. @anirudhdharmarajan can talk a bit more about this but right now we do have a mapping of `document_ids` to internal `pids` (passage_ids) at indexing time. This mapping could be used to make it so `search()` would only look within `pids` that are mapped to `document_ids` specified by the user, producing the behaviour you're requesting.

**Comment by PrimoUomo89** [comment]
I had looked a bit at the pids when reviewing @anirudhdharmarajan 's pull request for document_metadata so a little familiar with what you're describing. I'll take a rough swing this week, but it's possible I'm out of my depth. Will look for feedback when I have a a plan.

**Comment by PrimoUomo89** [comment]
@bclavie python really isn't my language but I think I have a good approach. I did most of it but I wanted your input:

In models/colbert.py, I modified search to allow for sending a list of docids as a subset to be searched. If it's passed in, I've done the filtering and temporary mapping, to get the subset id to the pid, and I've resolved the appropriate docids returns from the search. I've also allowed for passing a subset_collection to _load_searcher.

My issue is the _load_searcher function which saves the searcher to self. I have two possible approaches in mind:
1. If querying a subset, pass a boolean to _load_searcher which doesn't set the searcher to self, but instead, returns the searcher as a "temporary searcher". I like this as I can set a "searcher_to_use" in the calling function, which follows my current pattern "collection_to_use", etc...
2. If querying a subset, save a flag to self which indicates that no matter what the next search is, reload the searcher. This is probably the easiest, but may be a bit strange (a force reload searcher flag).

Let me know what you think if you time. Otherwise I'll choose one and pass it to a pull request.

**Comment by PrimoUomo89** [comment]
@bclavie or @anirudhdharmarajan Sorry for all the comments. I made it to this point:

Searcher(
                checkpoint=self.checkpoint,
                config=None,
                collection=subset_collection,
                index_root=self.config.root,
                index=temp_index_name,
            )
            
Assuming subset_collection contains just the subset of documents, should this searcher not work? I think I'm missing something...

**Comment by PrimoUomo89** [comment]
Deleted my previous comments because it had the wrong approach. Will send a pull request later today hopefully.

**Comment by PrimoUomo89** [comment]
Pull Request complete.

**Comment by hehuan2363** [comment]
Are you refering to something similar to this issue in Colbert: https://github.com/stanford-futuredata/ColBERT/issues/304

**Comment by PrimoUomo89** [comment]
@hehuan2363 
The main difference between what I implemented for this issue and what they're discussing on that issue, is that instead of implementing access to the filter lamda function, I instead implemented access to submitting document_ids (which are resolved to pids before search). I'm not sure what the best implementation would be on this side, but I imagine a lamda function which resolves document_ids in RAGatouille, which would then resolve the pids to search. If someone asks for it, I'll help out with that.

**Comment by bclavie** [comment]
> Pull

Thank you! Closing this issue as it's been merged

**Comment by dimittal** [comment]
@bclavie 
I have a list of document_ids i want to filter the index first before searching in it. 

I referred to https://github.com/stanford-futuredata/ColBERT/issues/304 and did this:

```
def keepResult(query, index, document_ids):
    if index in document_ids:
        return True
    return False
```

```
RAG = RAGPretrainedModel.from_index(<index_file_path>)
results = RAG.search(query_title, k=top_k, filter_fn=lambda pids: torch.tensor([index for index in pids.numpy().tolist() if keepResult(query, index, document_ids)], dtype=pids.dtype))
```

But I am getting `TypeError: ColBERT.search() got an unexpected keyword argument 'filter_fn'`

I am using `RAGatouille==0.0.8.post4`
