### ISSUE TITLE
missing srsly

### ISSUE THREAD

**Issue by fpservant** [bclavie/RAGatouille#89]
Hi,
after pip install ragatouille on GCP (VertexAI), missing 'srsly'
srsly, seriously?  Not so serious:
pip install srsly
solves the problem

**Comment by bclavie** [comment]
Whoops! Accidentally broke this when cleaning up dependencies yesterday, pushing a fix in a couple minutes. Thanks for raising!

**Comment by bclavie** [comment]
(resolved in 0.0.6b2)
