### ISSUE TITLE
RAGatouille seems to break when ingesting the colbertv2 pdf? 

### ISSUE THREAD

**Issue by jerryjliu** [bclavie/RAGatouille#9]
used llamaindex to parse colbertv2 arxiv pdf into 20 docs, tried putting the text into RAGatouillle, and getting the below error.

seems to work on first 5 docs and first 10 docs for some reason.

getting this error: 
```
File ~/Programming/llama-hub/.venv/lib/python3.10/site-packages/ragatouille/models/colbert.py:253, in ColBERT.search(self, query, index_name, k, force_fast, zero_index_ranks)
    249     result_for_query = []
    250     for id_, rank, score in zip(*result):
    251         result_for_query.append(
    252             {
--> 253                 "content": self.searcher.collection[id_],
    254                 "score": score,
    255                 "rank": rank - 1 if zero_index_ranks else rank,
    256             }
    257         )
    258     to_return.append(result_for_query)
    260 if len(to_return) == 1:

File ~/Programming/llama-hub/.venv/lib/python3.10/site-packages/colbert/data/collection.py:25, in Collection.__getitem__(self, item)
     23 def __getitem__(self, item):
     24     # TODO: Load from disk the first time this is called. Unless self.data is already not None.
---> 25     return self.data[item]

IndexError: list index out of range
```

Here's the notebook https://drive.google.com/file/d/1qEpaFSe7Vjhw4hOWHYc2wg49TLo9jCPI/view?usp=sharing

**Comment by bclavie** [comment]
Hey Jerry, thank you for flagging, and apologies for the growing pains!

This is a corollary of #3 and the fix for it not being properly applied when the index is still in-memory. I just pushed version `0.0.1c` which should fix the issue (your notebook runs fine with it, thanks a lot for the easy reproducibility), let me know if any other issue pops up!

**Comment by jerryjliu** [comment]
thanks!
