### ISSUE TITLE
how to define the path to an index when creating it?

### ISSUE THREAD

**Issue by fpservant** [bclavie/RAGatouille#90]
index() has an index_name param, but not a path.
The index is created in "./.ragatouille/colbert/indexes/index_name/" - how to choose this path? It's at least not clear in the doc. (Having a name starting with "." can be annoying, as you often do not see it)

**Comment by anirudhdharmarajan** [comment]
When initializing `RAGPretrainedModel` using `.from_pretrained()`, you can pass the optional `index_root` param and set it to whatever you'd like! 
So for example, using `index_root="my_root_dir"` would yield `my_root_dir/colbert/indexes/index_name/` after creating the index.
It's on my todo's to better document that.

**Comment by fpservant** [comment]
thx! I had missed it

**Comment by bclavie** [comment]
Will try to have this better documented in the (long overdue) doc update!
