### ISSUE TITLE
Colbert rerank not working, no attribute "run_context"

### ISSUE THREAD

**Issue by julianmukaj** [bclavie/RAGatouille#91]
\appdata\local\programs\python\python39\lib\site-packages\ragatouille\models\colbert.py", line 752, in __del__
AttributeError: 'ColBERT' object has no attribute 'run_context'

Have tried all versions of RAGatouille, this is on windows and on several Py versions 3.8, 3.9, 3.10 have been tested. 

I saw issue #40 fixed it for RAGtrainer but this happens when I load RAGPretrainedModel

**Comment by PrimoUomo89** [comment]
I think when no run_context is found, it can't find the index directory. When running from_index, I have to submit the full path to dir. not sure if that's intended.

**Comment by julianmukaj** [comment]
You should be able to do this without an index

```
colbert = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")
docs = colbert.rerank(query='What is ERS?', documents=[
    d['content'] for d in docs
], k=5)
```

But for the exception above is given on the line:

`colbert = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")`

Indicating a issue with RAGPretrainedModel class it seems, will take a deeper look soon

**Comment by PrimoUomo89** [comment]
My mistake. I misread your initial comment.

**Comment by bclavie** [comment]
>  When running from_index, I have to submit the full path to dir. not sure if that's intended.

If I understand correctly, this is intended yes! Maybe it's not super intuitive 🤔 

@julianmukaj It seems like this is likely hiding another error, as `__del__` shouldn't be called without an initialised run_context, which appears whenever a new ColBERT is instantiated... I've pushed a mini-PR to make `__del__` have a try/except, could you please try the latest version and let me know if it fixes it and/or reveals another real error?

**Comment by bclavie** [comment]
> I think fair to add library is currently not supported for Windows outside of WSL.

Yeah this is fair. I've juste added a disclaimer to the README to this effect -- windows support right now is a nice to have but sadly not something we can target with current resources
