### ISSUE TITLE
Scalability question

### ISSUE THREAD

**Issue by DavidGOrtega** [bclavie/RAGatouille#98]
@bclavie Im interested in is in scalability. How much requests allows at the same time? Do you ever run any kind of test like this one?

**Comment by bclavie** [comment]
Hey David, not 100% sure exactly what you mean. RAGatouille isn't super focused on serving requests so it'd depend on your architecture. In terms of throughput:

- A ColBERT index is extremely optimised and queried super quickly
- The option of storing embedding without the index optimisation is also there, but would take a bit longer depending on how many docs you have. I'm working on making this simpler!

**Comment by DavidGOrtega** [comment]
Thanks for the reply @bclavie 🙏 

> Hey David, not 100% sure exactly what you mean. 

Simple, how many requests per second is able to handle? 
We should do a benchmark comparing it with SBert and a simple ann algorithm.

I have been reading the paper WikiChat and the wikipedia data is a solid 100GB in memory which is pretty big. Im interested in ColBert but specially if it is resources wise.
