### ISSUE TITLE
query length

### ISSUE THREAD

**Issue by fpservant** [bclavie/RAGatouille#99]
Hi,
document can be long, and there is this max_document_length and the possibility to split a document during indexing.
But a query also could be long.
Is this handled somehow in the API, or should I deal with it myself? What happens when I just search for a query that is longer than what colbert supports?
TIA

**Comment by bclavie** [comment]
Hey, this is a good point. The querying implementation is naive and assumes small query which is the main use case, but it should be extended to dynamically adapt to the length of the current query. Tagging this as a Help Wanted issue and adding to the to-do list for upcoming releases.

> What happens when I just search for a query that is longer than what colbert supports?

If you search for a query longer than what's set as the max query (currently 32, can be up to 512/whatever the base model ColBERT was trained off allows), it'll be truncated to the max length (just like passing a document that's too long to a tokeniser with a set max length).

**Comment by fpservant** [comment]
thanks!

**Comment by bclavie** [comment]
Closing the issue as 0.0.7post2 onwards now has dynamic query size adjustment (from 32 to the base model's max position embeddings)
